import { Wix_Madefor_Text } from "next/font/google";
import "./globals.css";


const Text = Wix_Madefor_Text({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-Wix_Madefor_Text',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Text.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
